image: registry.inhand.local/inhandtest/python3:latest
stages:
  - test

test_ui_auto:
  stage: test
  script:
    - python run.py
  artifacts:
    paths:
      - Report/allure-report
    expire_in: 1 week
  only:
    - luozw-ui-auto
