allure_environment:
  URL: http://beta.inconnect.inhand.design/
  description: test description
  username: luozw@inhand.com.cn
  version: V0.12.0
local_distributed_config:
  node1:
    browser: firefox
    host: http://127.0.0.1:4444/wd/hub
  node2:
    browser: chrome
    host: http://127.0.0.1:4444/wd/hub
local_driver_conf:
  browser: chrome
  host: http://127.0.0.1:4444/wd/hub
  node: node2
