allure_environment:
  URL: http://beta.inconnect.inhand.design/
  description: test description
  username: luozw@inhand.com.cn
  version: V0.12.0
test_info:
  test_URL: https://snail.zhuozhuo.io/?n=fastCat.fcFrontSnail.NewFront.NewFront.PCLoginPage
